# Fundamentals Understanding Tensorflow Library


In [2]:
import tensorflow as tf
import numpy as np

## Basic

In [6]:
# importing library of the tensorflow
import tensorflow as tf

In [4]:
# checking installed version of the tenrsoflow(other libraries)
print(tf.__version__)

2.9.1


In [6]:
# creating constant tensor
const_v = tf.constant(7)

# creating dynamic tensor
dyna_v = tf.Variable(10)

const_v, dyna_v

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>)

In [127]:
# creating different levels of tensor
  # hard coded version
  
scalar_v = tf.Variable([1,2,3,4,5,6,7,8,9,10])

vector_v = tf.Variable([
  [1,2,3],
  [4,5,6]
])

matrix_v = tf.Variable([
  [
    [1,2,3],
    [4,5,6],
    [6,7,8]
  ],
  [
    [9,10,11],
    [12,13,14],
    [15,16,17]
  ]
])
tensor_v = tf.Variable([
  [
    [
      [1,2],
      [3,4],
      [5,6]
    ],
    [
      [7,8],
      [9,10],
      [11,12]
    ],
    [
      [13,14],
      [15,16],
      [17,18]
    ]
  ],
  [
    [
      [19,20],
      [21,22],
      [23,24]
    ],
    [
      [25,26],
      [27,28],
      [29,30]
    ],
    [
      [31,32],
      [33,34],
      [35,36]
    ]
  ]
])

scalar_v, vector_v, matrix_v, tensor_v

(<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>,
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])>,
 <tf.Variable 'Variable:0' shape=(2, 3, 3, 2) dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16],
          [17, 18]]],
 
 
        [[[19, 20],
          [21, 22],
          [23, 24]],
 
         [[25, 26],
          [27, 28],
          [29, 30]],
 
         [[31, 32],
          [33, 34],
          [35, 36]]]])>)

In [128]:
# collecting certain data of the tensor variable
print("--- Scalar ---")
print("Dimension : ", tf.constant(scalar_v).ndim)
print("Data type :", scalar_v.dtype)
print("Shape :", scalar_v.shape)
print("Total number of elements in our tensor :", tf.size(scalar_v))
print("\n")

print("--- Vectors ---")
print("Dimension : ", tf.constant(vector_v).ndim)
print("Data type :", vector_v.dtype)
print("Shape :", vector_v.shape)
print("Total number of elements in our tensor :", tf.size(vector_v))
print("\n")

print("--- Matrix ---")
print("Dimension : ", tf.constant(matrix_v).ndim)
print("Data type :", matrix_v.dtype)
print("Shape :", matrix_v.shape)
print("Total number of elements in our tensor :", tf.size(matrix_v))
print("\n")

print("--- Tensor of 4 ---")
print("Dimension : ", tf.constant(tensor_v).ndim)
print("Data type :", tensor_v.dtype)
print("Shape :", tensor_v.shape)
print("Total number of elements in our tensor :", tf.size(tensor_v))
print("\n")

--- Scalar ---
Dimension :  1
Data type : <dtype: 'int32'>
Shape : (10,)
Total number of elements in our tensor : tf.Tensor(10, shape=(), dtype=int32)


--- Vectors ---
Dimension :  2
Data type : <dtype: 'int32'>
Shape : (2, 3)
Total number of elements in our tensor : tf.Tensor(6, shape=(), dtype=int32)


--- Matrix ---
Dimension :  3
Data type : <dtype: 'int32'>
Shape : (2, 3, 3)
Total number of elements in our tensor : tf.Tensor(18, shape=(), dtype=int32)


--- Tensor of 4 ---
Dimension :  4
Data type : <dtype: 'int32'>
Shape : (2, 3, 3, 2)
Total number of elements in our tensor : tf.Tensor(36, shape=(), dtype=int32)




In [25]:
# using other automated datatype
string_v = tf.Variable(["abc","def","ghi"])
float_v = tf.Variable([1.0, 1.1, 1.2])

string_v, float_v

(<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'abc', b'def', b'ghi'], dtype=object)>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1. , 1.1, 1.2], dtype=float32)>)

In [31]:
# setting user defined data type
  # direct int to float is valid
float_vdc = tf.Variable([
  [1,2,3],
  [4,5,6],
  [6,7,8]
], dtype=tf.float32)

print(float_vdc)

  # but float to int has process and can't be direct
int_vdc = tf.Variable([
  [1.0,1.1,1.2],
  [2.0,2.1,2.2]
], dtype=tf.int32)

print(int_vdc)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float32)>


TypeError: Cannot convert [[1.0, 1.1, 1.2], [2.0, 2.1, 2.2]] to EagerTensor of dtype int32

In [38]:
# changing value inside variable
change_vt = tf.Variable([1,2,3,4,5])
unchangable_vt = tf.constant([1,2,3,4,5])

print(change_vt)

change_vt = change_vt[0].assign(100)

print("Change")
print(change_vt)

print(unchangable_vt)
print('\n')

print("Error appear, can't be change")
unchangable_vt = unchangable_vt[1].assign(100)
print(unchangable_vt)


<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5])>
Change
<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([100,   2,   3,   4,   5])>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


Error appear, can't be change


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

##### Indexing Tensor

In [157]:
# Calling whole array
print("Complete Array : ", scalar_v[:], "\n")

# Calling single index
print("Single Index : ", scalar_v[0], "\n")

# Calling Range Index
print("Range index : ", scalar_v[0:3], "\n")

# Calling Open Range Index
print("Open Range index start: ", scalar_v[:4])
print("Open Range index end: ", scalar_v[3:], "\n")

# Calling Dimensional Index
print("Dimensional Index, specific : ", vector_v[0,1])
print("Dimensional Index, range specific : ", tensor_v[0:2,1:3])
print("Dimensional Index, open range : ", tensor_v[:1,:2])
print("Dimensional Index, mix : ", tensor_v[0:1,:2,1])

# Calling the end array
print("End index start: ", scalar_v[-1])




Complete Array :  tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32) 

Single Index :  tf.Tensor(1, shape=(), dtype=int32) 

Range index :  tf.Tensor([1 2 3], shape=(3,), dtype=int32) 

Open Range index start:  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Open Range index end:  tf.Tensor([ 4  5  6  7  8  9 10], shape=(7,), dtype=int32) 

Dimensional Index, specific :  tf.Tensor(2, shape=(), dtype=int32)
Dimensional Index, range specific :  tf.Tensor(
[[[[ 7  8]
   [ 9 10]
   [11 12]]

  [[13 14]
   [15 16]
   [17 18]]]


 [[[25 26]
   [27 28]
   [29 30]]

  [[31 32]
   [33 34]
   [35 36]]]], shape=(2, 2, 3, 2), dtype=int32)
Dimensional Index, open range :  tf.Tensor(
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]], shape=(1, 2, 3, 2), dtype=int32)
Dimensional Index, mix :  tf.Tensor(
[[[ 3  4]
  [ 9 10]]], shape=(1, 2, 2), dtype=int32)
Open Range index start:  tf.Tensor(10, shape=(), dtype=int32)


## Generator

- Zero
- One
  - int and float
- Incremental
- Random

##### Zero and One

In [65]:
# default
zero_gv = tf.zeros([3,2])

one_gv = tf.ones([4,3,2])

# custom zero
  # custom one are invalid
zero_cgv = tf.zeros([4,3], dtype=tf.int32)

one_cgv = tf.ones([4,3], dtype=tf.int32)

print("Default Zero and One")
print(zero_gv, one_gv)
print('\n')

print("Customed Zero and Ones")
print(zero_cgv, one_cgv)

Default Zero and One
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32) tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(4, 3, 2), dtype=float32)


Customed Zero and Ones
tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]], shape=(4, 3), dtype=int32) tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(4, 3), dtype=int32)


##### Incremental

In [ ]:
math_v = tf.range(1,10)
math_v

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [2]:
import numpy as np

In [49]:
print(np.__version__)

1.23.0


In [80]:
# Using Numpy
  # arange
    # (input) 1 = (equivalent) end
    # 2 = start, stop
    # 3 = start, stop, step
      # dtype must have numpy data type
tensor3_rv = np.arange(2)
print("1 input : ",tensor3_rv)
tensor3_rv = np.arange(2,6)
print("2 input : ",tensor3_rv)
tensor3_rv = np.arange(2,6,2)
print("3 input : ",tensor3_rv)
tensor3_rv = np.arange(2,6,2,dtype=np.float32)
print("3 and dtype input : ",tensor3_rv)
print("Note: data type should be numpy/np")


1 input :  [0 1]
2 input :  [2 3 4 5]
3 input :  [2 4]
3 and dtype input :  [2. 4.]
Note: data type should be numpy/np


##### Random

In [40]:
# Using Tensor to randomize
  # using seed
    # in normal distribution with shape as pre-requisite input
tensor1_rv = tf.random.Generator.from_seed(1)
tensor1_rv = tensor1_rv.normal(shape=(3,2))

    # in uniform distribution with shape as pre-requisite input
      # with optional minval, maxval and/or dtype
tensor2_rv = tf.random.Generator.from_seed(2)
tensor2_rv = tensor2_rv.uniform(shape=(3,2), minval=1, maxval=10, dtype=tf.int32)

tensor1_rv, tensor2_rv


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[9, 5],
        [1, 4],
        [2, 7]])>)

In [78]:
#using Numpy
  # random
    # randint
      # randint(min, max)
tensor4_rv = np.random.randint(0,100)
print("min and max : ",tensor4_rv)
      # randint(min, max, shape)
tensor4_rv = np.random.randint(0,100,[2,3])
print("min, max and shape : ",tensor4_rv)
tensor4_rv = np.random.randint(0,100,[2,3],dtype=np.int16)
print("min, max, shape and dtype of int : ", tensor4_rv)
print("Note: data type of int and np only")

min and max :  8
min, max and shape :  [[16 77 33]
 [70 55 31]]
min, max, shape and dtype of int :  [[79 97 82]
 [61 41 30]]
Note: data type of int and np only


In [232]:
    # random
      # 
tensor5_rv = np.random.random([2,3])
print(tensor5_rv)
      # additional randomization
tensor6_rv = np.random.random([2,3]) * 100
print(tensor6_rv)


[[0.50917243 0.99868948 0.66799058]
 [0.4715337  0.24978142 0.35427653]]
[[24.12928714 82.09885057 65.14376155]
 [89.58301766 31.17560145 40.99471473]]


## Shuffle, Sort and Seed

In [35]:
nShuffled1_v = tf.constant([np.random.randint(0,100,5)])
nShuffled1_v = tf.Variable(nShuffled1_v)

nShuffled2_v = tf.constant([np.random.randint(0,100,(2,3))])
nShuffled2_v = tf.Variable(nShuffled2_v)

nShuffled3_v = tf.constant([np.random.randint(0,100,(2,3,4))])
nShuffled3_v = tf.Variable(nShuffled3_v)

Sample 1 Not Shuffuled :  <tf.Variable 'Variable:0' shape=(1, 5) dtype=int32, numpy=array([[ 8, 47, 62, 83, 81]])> 

Sample 2 Not Shuffuled :  <tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=int32, numpy=
array([[[35, 68, 54],
        [40, 47, 90]]])> 

Sample 3 Not Shuffuled :  <tf.Variable 'Variable:0' shape=(1, 2, 3, 4) dtype=int32, numpy=
array([[[[64, 54, 77, 91],
         [74,  9, 95, 81],
         [50, 77, 63, 28]],

        [[92, 77, 20, 39],
         [16, 85, 38, 96],
         [93, 46, 79, 76]]]])> 



##### Shuffle

In [80]:
# using random.shuffle()
  # it requires which deep using index as indication
shuffled1_v = tf.random.shuffle(nShuffled1_v[0])
print("Sample 1 Not Shuffuled : ",nShuffled1_v, "\n")
print("Sample 1 : ",shuffled1_v,"\n")

print("----------------------------------------------------------------\n")

print("Sample 2 Not Shuffuled : ",nShuffled2_v, "\n")
print("-- Does not change: because there is no index --")
shuffled2_v = tf.random.shuffle(nShuffled2_v)
print("Sample 2 : ",shuffled2_v,"\n")

shuffled2_v = tf.random.shuffle(nShuffled2_v[0,0])
print("Sample 2 index 0,0: ",shuffled2_v)
shuffled2_v = tf.random.shuffle(nShuffled2_v[0,1])
print("Sample 2 index 0,1: ",shuffled2_v,"\n")

print("----------------------------------------------------------------\n")

print("Sample 3 Not Shuffuled : ",nShuffled3_v, "\n")
print("-- Shuffle the dimension 2 --")
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,0])
print("Sample 3 0,0 : ", shuffled3_v,"\n")
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,1])
print("Sample 3 0,1 : ", shuffled3_v,"\n")

print("-- Shuffle the dimension 3 --")
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,0,0])
print("Sample 3 0,0,0 : ", shuffled3_v)
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,0,1])
print("Sample 3 0,0,1 : ", shuffled3_v)
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,0,2])
print("Sample 3 0,0,2 : ", shuffled3_v,"\n")

shuffled3_v = tf.random.shuffle(nShuffled3_v[0,1,0])
print("Sample 3 0,1,0 : ", shuffled3_v)
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,1,1])
print("Sample 3 0,1,1 : ", shuffled3_v)
shuffled3_v = tf.random.shuffle(nShuffled3_v[0,1,2])
print("Sample 3 0,1,2 : ", shuffled3_v)

Sample 1 Not Shuffuled :  <tf.Variable 'Variable:0' shape=(1, 5) dtype=int32, numpy=array([[ 8, 47, 62, 83, 81]])> 

Sample 1 :  tf.Tensor([81 47 83 62  8], shape=(5,), dtype=int32) 

----------------------------------------------------------------

Sample 2 Not Shuffuled :  <tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=int32, numpy=
array([[[35, 68, 54],
        [40, 47, 90]]])> 

-- Does not change: because there is no index --
Sample 2 :  tf.Tensor(
[[[35 68 54]
  [40 47 90]]], shape=(1, 2, 3), dtype=int32) 

Sample 2 index 0,0:  tf.Tensor([54 68 35], shape=(3,), dtype=int32)
Sample 2 index 0,1:  tf.Tensor([47 40 90], shape=(3,), dtype=int32) 

----------------------------------------------------------------

Sample 3 Not Shuffuled :  <tf.Variable 'Variable:0' shape=(1, 2, 3, 4) dtype=int32, numpy=
array([[[[64, 54, 77, 91],
         [74,  9, 95, 81],
         [50, 77, 63, 28]],

        [[92, 77, 20, 39],
         [16, 85, 38, 96],
         [93, 46, 79, 76]]]])> 

-- Shuffle the 

##### Sort

In [98]:
print("Original 1 : ",nShuffled1_v)
sorted1_v = tf.sort(nShuffled1_v, direction="ASCENDING")
print("Sorted 1 - A : ", sorted1_v)
sorted1_v = tf.sort(nShuffled1_v, direction="DESCENDING")
print("Sorted 1 - D : ", sorted1_v, "\n")

print("----------------------------------------------------------------\n")

print("Original 2 : ",nShuffled2_v)
sorted2_v = tf.sort(nShuffled2_v, direction="ASCENDING")
print("Sorted 2 - A : ", sorted2_v)
sorted2_v = tf.sort(nShuffled2_v, direction="DESCENDING")
print("Sorted 2 - D : ", sorted2_v, "\n")

print("----------------------------------------------------------------\n")

print("Original 3 : ",nShuffled3_v)
sorted3_v = tf.sort(nShuffled3_v, direction="ASCENDING")
print("Sorted 3 - A : ", sorted3_v)
sorted3_v = tf.sort(nShuffled3_v, direction="DESCENDING")
print("Sorted 3 - D : ", sorted3_v, "\n")

print("----------------------------------------------------------------")
print("                           With Axis\n")
print("can't understand the use case of the axis")

Original 1 :  <tf.Variable 'Variable:0' shape=(1, 5) dtype=int32, numpy=array([[ 8, 47, 62, 83, 81]])>
Sorted 1 - A :  tf.Tensor([[ 8 47 62 81 83]], shape=(1, 5), dtype=int32)
Sorted 1 - D :  tf.Tensor([[83 81 62 47  8]], shape=(1, 5), dtype=int32) 

----------------------------------------------------------------

Original 2 :  <tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=int32, numpy=
array([[[35, 68, 54],
        [40, 47, 90]]])>
Sorted 2 - A :  tf.Tensor(
[[[35 54 68]
  [40 47 90]]], shape=(1, 2, 3), dtype=int32)
Sorted 2 - D :  tf.Tensor(
[[[68 54 35]
  [90 47 40]]], shape=(1, 2, 3), dtype=int32) 

----------------------------------------------------------------

Original 3 :  <tf.Variable 'Variable:0' shape=(1, 2, 3, 4) dtype=int32, numpy=
array([[[[64, 54, 77, 91],
         [74,  9, 95, 81],
         [50, 77, 63, 28]],

        [[92, 77, 20, 39],
         [16, 85, 38, 96],
         [93, 46, 79, 76]]]])>
Sorted 3 - A :  tf.Tensor(
[[[[54 64 77 91]
   [ 9 74 81 95]
   [28 50 63

##### Seed
 - Using global or operational seed affects the randomness
 - Using global and operational seed randomize at first and constantly repeat the randomed data

## Other Tensor Manipulation

- Adding Dimension
- Squeezing Dimension
- Reshaping

In [189]:
tensorMan_v = np.random.randint(0,100,[4,4])
print("Dimension : ", tensorMan_v.ndim, "\n",
      "Shape : ", tensorMan_v.shape)
print(tensorMan_v)

Dimension :  2 
 Shape :  (4, 4)
[[37 43 23 22]
 [ 4 79 78 47]
 [38 56 77 36]
 [83 79 19 40]]


##### Adding Dimension

In [180]:
# Old Way
tensorMan_v = tensorMan_v[..., tf.newaxis]
tensorMan_v.ndim, tensorMan_v.shape

(3, TensorShape([2, 3, 1]))

In [181]:
# New Way
  # axis dictates where to add single dimension
tensorMan_v = tf.expand_dims(tensorMan_v,axis=0)
tensorMan_v.ndim, tensorMan_v.shape

(4, TensorShape([1, 2, 3, 1]))

##### Squeezing Dimension

In [182]:
tensorMan_v = tf.squeeze(tensorMan_v)
tensorMan_v.ndim, tensorMan_v.shape

(2, TensorShape([2, 3]))

##### Reshaping

In [191]:
print("Original\n")
print("Dimension : ", tensorMan_v.ndim, "\n",
      "Shape : ", tensorMan_v.shape)
print(tensorMan_v)

print("\n----------------------------------------------------------------\n")

tensorMan_v = tf.reshape(tensorMan_v, shape=[2,4,2])
print("Reshaped\n")
print("Dimension : ", tensorMan_v.ndim, "\n",
      "Shape : ", tensorMan_v.shape)
print(tensorMan_v)

Original

Dimension :  3 
 Shape :  (2, 4, 2)
tf.Tensor(
[[[37 43]
  [23 22]
  [ 4 79]
  [78 47]]

 [[38 56]
  [77 36]
  [83 79]
  [19 40]]], shape=(2, 4, 2), dtype=int32)

----------------------------------------------------------------

Reshaped

Dimension :  3 
 Shape :  (2, 4, 2)
tf.Tensor(
[[[37 43]
  [23 22]
  [ 4 79]
  [78 47]]

 [[38 56]
  [77 36]
  [83 79]
  [19 40]]], shape=(2, 4, 2), dtype=int32)


## Tensor Operations

- Basic Tensor Operations
- Rounding off
- Math Matrix
- Casting

##### Basic Tensor operation

In [3]:
operation_v = np.random.randint(0,100,[4,4])
operation_v

array([[30, 44, 38,  5],
       [24, 42, 97, 84],
       [79, 65, 69, 94],
       [31,  6, 34, 42]])

In [4]:
print(operation_v + 100)

[[130 144 138 105]
 [124 142 197 184]
 [179 165 169 194]
 [131 106 134 142]]


In [5]:
print(operation_v - 10)

[[20 34 28 -5]
 [14 32 87 74]
 [69 55 59 84]
 [21 -4 24 32]]


In [7]:
print(operation_v / 2.1)

[[14.28571429 20.95238095 18.0952381   2.38095238]
 [11.42857143 20.         46.19047619 40.        ]
 [37.61904762 30.95238095 32.85714286 44.76190476]
 [14.76190476  2.85714286 16.19047619 20.        ]]


In [8]:
print(operation_v * 2)

[[ 60  88  76  10]
 [ 48  84 194 168]
 [158 130 138 188]
 [ 62  12  68  84]]


##### Rounding Off

In [14]:
np.around(operation_v / 2.1, 2)

array([[14.29, 20.95, 18.1 ,  2.38],
       [11.43, 20.  , 46.19, 40.  ],
       [37.62, 30.95, 32.86, 44.76],
       [14.76,  2.86, 16.19, 20.  ]])

In [20]:
tf.math.round(operation_v / 2.1)

<tf.Tensor: shape=(4, 4), dtype=float64, numpy=
array([[14., 21., 18.,  2.],
       [11., 20., 46., 40.],
       [38., 31., 33., 45.],
       [15.,  3., 16., 20.]])>

In [18]:
print(tf.math.floor(operation_v / 2.1))

tf.Tensor(
[[14. 20. 18.  2.]
 [11. 20. 46. 40.]
 [37. 30. 32. 44.]
 [14.  2. 16. 20.]], shape=(4, 4), dtype=float64)


In [19]:
print(tf.math.ceil(operation_v / 2.))

tf.Tensor(
[[15. 22. 19.  3.]
 [12. 21. 49. 42.]
 [40. 33. 35. 47.]
 [16.  3. 17. 21.]], shape=(4, 4), dtype=float64)


##### Matrix multiplication

In [201]:
tf.matmul(operation_v, operation_v)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[10702,  5488,  1614, 10188],
       [ 9493,  4945,  1446,  8660],
       [ 9818,  4654,  1842,  8542],
       [ 3409,  1896,   658,  2877]])>

In [202]:
operation_v @ operation_v

array([[10702,  5488,  1614, 10188],
       [ 9493,  4945,  1446,  8660],
       [ 9818,  4654,  1842,  8542],
       [ 3409,  1896,   658,  2877]])

##### Casting

In [225]:
casting_v = np.random.randint(0,100,[3,5])

In [226]:
print("Original : ", casting_v.dtype)
casting_v = tf.cast(casting_v, dtype=tf.float32)
print("Casted : ", casting_v.dtype)


Original :  int32
Casted :  <dtype: 'float32'>


## Aggregators

- Mathematical Operations
- Reduce
- Math
- TF Probability (Library)
- Positional

In [3]:
agre_v = tf.Variable(np.random.random([3,4,3]) * -100)
agre_v

<tf.Variable 'Variable:0' shape=(3, 4, 3) dtype=float64, numpy=
array([[[-43.29523927, -73.08631388, -64.72027526],
        [-81.50669459,  -2.80812643, -72.18414434],
        [-46.75968307, -98.02701207, -24.26655037],
        [-90.80773543,  -9.53051125, -15.82949869]],

       [[-95.26312764, -67.78464317, -93.97492105],
        [-29.10949125, -14.68817305, -30.10905816],
        [ -5.1056148 ,  -6.09709755, -23.17353124],
        [-39.8084409 , -40.33628738, -15.05566375]],

       [[-64.48396859, -86.07435189, -64.14697118],
        [-84.82079839, -92.29893921, -90.85836909],
        [-64.68701358, -98.351133  , -74.53153735],
        [-59.09728047, -98.94961664, -44.29202601]]])>

##### Mathematical Operations

In [281]:
tf.abs(agre_v)

<tf.Tensor: shape=(3, 4, 3), dtype=float64, numpy=
array([[[82.49434263, 95.45860454, 77.62156587],
        [26.44985768, 21.23091096, 53.01743221],
        [87.86384548, 37.42504993, 42.64930215],
        [34.67124385, 56.69797445, 58.13019191]],

       [[37.03614759, 80.87596844, 53.43412292],
        [57.61384254, 20.61976313,  2.1504781 ],
        [ 9.85920322, 73.75262094, 76.26891001],
        [80.98345779, 47.06482819, 86.63258628]],

       [[86.36443825,  2.90957027, 55.55978064],
        [71.36175366, 10.55552952, 28.403683  ],
        [36.16013607, 71.88603572, 63.17002092],
        [82.93999848, 33.69555274, 62.85272245]]])>

In [282]:
tf.square(agre_v)

<tf.Tensor: shape=(3, 4, 3), dtype=float64, numpy=
array([[[6.80531657e+03, 9.11234518e+03, 6.02510749e+03],
        [6.99594971e+02, 4.50751580e+02, 2.81084812e+03],
        [7.72005534e+03, 1.40063436e+03, 1.81896297e+03],
        [1.20209515e+03, 3.21466031e+03, 3.37911921e+03]],

       [[1.37167623e+03, 6.54092227e+03, 2.85520549e+03],
        [3.31935485e+03, 4.25174632e+02, 4.62455608e+00],
        [9.72038882e+01, 5.43944910e+03, 5.81694663e+03],
        [6.55832044e+03, 2.21509805e+03, 7.50520501e+03]],

       [[7.45881619e+03, 8.46559918e+00, 3.08688923e+03],
        [5.09249989e+03, 1.11419203e+02, 8.06769208e+02],
        [1.30755544e+03, 5.16760213e+03, 3.99045154e+03],
        [6.87904335e+03, 1.13539027e+03, 3.95046472e+03]]])>

In [285]:
tf.sqrt(tf.cast(tf.abs(agre_v), dtype=tf.float32))

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[9.08264  , 9.770292 , 8.81031  ],
        [5.1429424, 4.6077013, 7.281307 ],
        [9.373571 , 6.1176014, 6.5306435],
        [5.8882294, 7.5298057, 7.6243157]],

       [[6.085733 , 8.993107 , 7.309865 ],
        [7.5903783, 4.540899 , 1.4664508],
        [3.139937 , 8.5879345, 8.733208 ],
        [8.999081 , 6.860381 , 9.307663 ]],

       [[9.293247 , 1.7057463, 7.453843 ],
        [8.447589 , 3.2489274, 5.3295107],
        [6.01333  , 8.478563 , 7.947957 ],
        [9.10714  , 5.804787 , 7.927971 ]]], dtype=float32)>

##### Reduce

In [6]:
tf.reduce_min(tf.abs(agre_v))

<tf.Tensor: shape=(), dtype=float64, numpy=2.8081264297747266>

In [7]:
tf.reduce_max(tf.abs(agre_v))

<tf.Tensor: shape=(), dtype=float64, numpy=98.94961663572411>

In [8]:
tf.reduce_mean(tf.abs(agre_v))

<tf.Tensor: shape=(), dtype=float64, numpy=55.719995555312444>

In [9]:
tf.reduce_prod(tf.abs(agre_v))

<tf.Tensor: shape=(), dtype=float64, numpy=2.1847983374939974e+58>

##### Math

In [10]:
tf.math.reduce_std(tf.abs(agre_v))

<tf.Tensor: shape=(), dtype=float64, numpy=31.307859004710906>

In [11]:
tf.math.reduce_std(tf.cast(agre_v, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.30786>

In [12]:
tf.math.log(tf.cast(tf.abs(agre_v), dtype=tf.float32))

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[3.7680426, 4.291641 , 4.1700745],
        [4.4006853, 1.0325176, 4.2792206],
        [3.8450212, 4.585243 , 3.1890988],
        [4.5087442, 2.2544982, 2.7618752]],

       [[4.556643 , 4.216336 , 4.543028 ],
        [3.3710642, 2.6870427, 3.4048262],
        [1.6303408, 1.8078128, 3.1430106],
        [3.684079 , 3.6972516, 2.7117543]],

       [[4.1664166, 4.4552116, 4.1611767],
        [4.440541 , 4.5250325, 4.509302 ],
        [4.1695604, 4.588544 , 4.3112226],
        [4.079185 , 4.5946107, 3.7908046]]], dtype=float32)>

In [15]:
tf.math.reduce_variance(agre_v)

<tf.Tensor: shape=(), dtype=float64, numpy=980.1820354588579>

##### TF probability

In [252]:
!pip install --upgrade tensorflow-probability


In [16]:
import tensorflow_probability as tfp


In [17]:
tfp.stats.variance(agre_v)

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[ 455.22003378,   59.03447653,  193.98550789],
       [ 651.13332716, 1574.79690033,  645.5020362 ],
       [ 622.93262922, 1884.66903268,  573.93426654],
       [ 442.0600365 , 1375.58829088,  185.05324   ]])>

##### Positional

In [258]:
# basic understanding of finding position
pos_v = np.random.random(5) * 100
print("Minimum Scalar")
print("ran_scalar Values: ", pos_v)
print("Position: ", tf.argmin(pos_v))
print("Value in Position: ", pos_v[tf.argmin(pos_v)])
print("\n")

print("Maximum Scalar")
print("pos_v Values: ", pos_v)
print("Position: ", tf.argmax(pos_v))
print("Value in Position: ", pos_v[tf.argmax(pos_v)])

Minimum Scalar
ran_scalar Values:  [45.36184221 42.61718564 89.27868221 42.7600731  38.21491789]
Position:  tf.Tensor(4, shape=(), dtype=int64)
Value in Position:  38.21491789361274


Maximum Scalar
pos_v Values:  [45.36184221 42.61718564 89.27868221 42.7600731  38.21491789]
Position:  tf.Tensor(2, shape=(), dtype=int64)
Value in Position:  89.27868220646448


## One-hot Encoding

In [265]:
indicies_list = np.arange(0, 5)
depth = 5

tf.one_hot(indicies_list, depth)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [266]:
tf.one_hot(indicies_list, depth, on_value="Here", off_value="...")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Here', b'...', b'...', b'...', b'...'],
       [b'...', b'Here', b'...', b'...', b'...'],
       [b'...', b'...', b'Here', b'...', b'...'],
       [b'...', b'...', b'...', b'Here', b'...'],
       [b'...', b'...', b'...', b'...', b'Here']], dtype=object)>

In [267]:
less_depth = 3

tf.one_hot(indicies_list, less_depth, on_value="Here", off_value="...")

<tf.Tensor: shape=(5, 3), dtype=string, numpy=
array([[b'Here', b'...', b'...'],
       [b'...', b'Here', b'...'],
       [b'...', b'...', b'Here'],
       [b'...', b'...', b'...'],
       [b'...', b'...', b'...']], dtype=object)>

## Experimental with Argmin/max

In [259]:
# experimental with:
#   creating using random
#   creating with shape in random
#   finding argmin/argmax of vectors

ran_vectors = np.random.random((3,2)) * 10
print(ran_vectors)
print(ran_vectors.shape[0])
print(ran_vectors.ndim)
print(tf.argmin(ran_vectors))

[[5.87111727 8.62576207]
 [4.04805644 4.67980355]
 [9.39509994 7.65296162]]
3
2
tf.Tensor([1 1], shape=(2,), dtype=int64)


In [260]:
tf.argmin(ran_vectors.shape)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [261]:
def indexing(value):
  return tf.argmax(value)


test_var = tf.zeros(ran_vectors.shape[0])
test_var = tf.cast(test_var,dtype=tf.float32)
test_var = tf.Variable(test_var)
i = 0
for item in ran_vectors:
  index = indexing(ran_vectors[i])
  test_var[i].assign(ran_vectors[i][index])
  i+=1
print(indexing(test_var))

tf.Tensor(2, shape=(), dtype=int64)
